### ISSUE TITLE
QEMU Support

### ISSUE THREAD

**Issue by Stebalien** [filecoin-project/ref-fvm#657]
Apparently, wasmtime has some QEMU issues:

```
RUST_BACKTRACE=full lotus-seed genesis car --out genesis.car genesis.json
init set t3wsjksusdymez76vsztzfw34r6fjh2nm7swvrqhyjqe3kxkwg34jmxxpqlgirwxxnelbbjwdnswjffnmoccta t0100
init set t1ceb34gnsc6qk5dt6n7xg6ycwzasjhbxm3iylkiy t0101
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
thread '<unnamed>' panicked at 'not implemented: cannot generate relocation against libcall CeilF64', /home/user/.cargo/git/checkouts/wasmtime-80f9cf5310d47b8e/cbb8a3d/crates/cranelift/src/obj.rs:264:21
stack backtrace:
   0:          0x2cbe8ed - std::backtrace_rs::backtrace::libunwind::trace::h02bdfeed412ba77b
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:          0x2cbe8ed - std::backtrace_rs::backtrace::trace_unsynchronized::h5721e9ec9537655b
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x2cbe8ed - std::sys_common::backtrace::_print_fmt::h10137ddb502bbd3d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:66:5
   3:          0x2cbe8ed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1437c86ead09a95e
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:45:22
   4:          0x2d1a68c - core::fmt::write::hdf7e5ac637575708
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/fmt/mod.rs:1196:17
   5:          0x2caffd1 - std::io::Write::write_fmt::h00341f121451a31a
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/io/mod.rs:1655:15
   6:          0x2cc1605 - std::sys_common::backtrace::_print::he4ececdb06ab9d22
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:48:5
   7:          0x2cc1605 - std::sys_common::backtrace::print::h55b32276835ed858
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:35:9
   8:          0x2cc1605 - std::panicking::default_hook::{{closure}}::h6999a27c7f7e27cf
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:295:22
   9:          0x2cc1279 - std::panicking::default_hook::hcc406adc7605c4f5
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:314:9
  10:          0x2cc1d28 - std::panicking::rust_panic_with_hook::haf8e1f62f460c64d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:698:17
  11:          0x2cc1bd7 - std::panicking::begin_panic_handler::{{closure}}::hf3a68aa6ac5cd357
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:588:13
  12:          0x2cbeda4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1515778c280a0daf
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:138:18
  13:          0x2cc1909 - rust_begin_unwind
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:584:5
  14:           0x61dca3 - core::panicking::panic_fmt::hfe413bf5e72d349d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/panicking.rs:142:14
  15:          0x2db315c - wasmtime_cranelift::obj::ObjectBuilder::append_func::h730d06fc64cb0b99
  16:          0x2db3270 - wasmtime_cranelift::obj::ObjectBuilder::func::h39b118a0eeacd738
  17:          0x222bf1f - <wasmtime_cranelift::compiler::Compiler as wasmtime_environ::compilation::Compiler>::emit_obj::hde0941181f918f89
  18:          0x220053e - wasmtime::module::Module::build_artifacts::h57c0bf57c21e2e6d
  19:          0x21ffec1 - wasmtime::module::Module::from_binary::hc7bdb52f657463ae
  20:          0x218f464 - fvm::machine::engine::Engine::load_raw::h1452979c5bb26ec4
  21:          0x2083868 - fvm::machine::engine::Engine::preload::h9bbaeb88c0c73576
  22:          0x1edddce - fvm::machine::default::DefaultMachine<B,E>::new::he9e8bf50248b3139
  23:          0x1e61156 - std::panicking::try::h6c9c6b772c4f5d0d
  24:          0x1e333c3 - filcrypto::util::types::catch_panic_response_no_default::h648a819436b7fcd9
  25:          0x1efaa09 - create_fvm_machine
  26:          0x19a5aca - _cgo_2731a736ee7f_Cfunc_create_fvm_machine
  27:           0x69f2d0 - runtime.asmcgocall
                               at /usr/local/go/src/runtime/asm_amd64.s:765
```

**Comment by kyle-parkinson** [comment]
Host information

rustc --print target-cpus
Available CPUs for this target:
    native         - Select the CPU of the current host (currently athlon-xp).

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Vendor ID:                       AuthenticAMD
CPU family:                      6              --- !!
Model:                           6   
Model name:                      QEMU Virtual CPU version 2.5+

**Comment by Stebalien** [comment]
We've updated from wasmtime 1.0 to 2.0.2. If this is still an issue (with the latest master) please file an issue and we'll report it to upstream.
